### ISSUE TITLE
Cannot install latest version

### ISSUE THREAD

**Issue by sylvainmetayer** [everpeace/asdf-docker-slim#2]
Hello,

On the docker-slim website and github repo, [version 1.32.0](https://github.com/docker-slim/docker-slim/releases/tag/1.32.0) is the latest version. However, it seems this plugin cannot find this version.

```
$ asdf install docker-slim 1.32.0
Downloading version 1.32.0 of docker-slim
Error: docker-slim version 1.32.0 not found
```

Here is the results of the found version by asdf : 

```
$ asdf list-all docker-slim 
1.11
1.14
1.15
1.16
1.17
1.18
1.19
1.20
1.21
1.22
1.23
1.24
```

**Comment by x80486** [comment]
It's been a while since this was raised. Would be nice to get some attention...probably an easy fix 🙄

**Comment by sylvainmetayer** [comment]
@x80486 I've submitted #3 which should fix this issue, if you want to take a look

**Comment by x80486** [comment]
Looks good to me 🍻
